name: CI-CD
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build App
      run: npm run build

    - name: Configure Git User
      run: |
        git config --global user.email "lucasand96@gmail.com"
        git config --global user.name "Lucas Anderson"

    - name: Authenticate with private NPM package
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Release NPM
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx release-it --no-git.requireCleanWorkingDir --ci